"""Generate the public marketplace tree and the Claude Desktop extension.

The output is what MemorySafe-Labs/memorysafe-plugin holds: one marketplace that both
Claude Code and Codex read, one plugin directory, and the workflow that turns a pushed
tag into a GitHub Release. It is generated and never edited in that repository, for the
same reason the beta download is generated: a hand-maintained copy kept handing testers
a build whose defects were already fixed.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_claude_packages import _SRC_NOT_SHIPPED, _draw_icon  # noqa: E402
from build_claude_packages import build as build_claude_packages  # noqa: E402
from plugin_meta import project_version  # noqa: E402


MARKETPLACE_NAME = "memorysafe"
PLUGIN_NAME = "memorysafe"
MCPB_NAME = "memorysafe-claude-desktop.mcpb"
INSTALL_GUIDE = "install-guide.png"
PUBLIC_REPOSITORY = "MemorySafe-Labs/memorysafe-plugin"
# scripts/release_plugin.py pushes each release's extension and notes on this branch
# prefix, and the public repository's own workflow turns them into a GitHub Release.
ASSET_BRANCH_PREFIX = "release-assets/"
NOTES_NAME = "notes.md"
# Only what a plugin host runs. manifest.json and mcpb_server.py belong to the Claude
# Desktop bundle and INSTALL.md to the beta download. The .cmd launchers DO ship: the
# launch line names an extensionless command and Windows resolves the extension.
# README.md is NOT copied: it is generated from plugin/README-template.md into both
# public locations, because two hand-kept READMEs drifted and lost the Windows
# migrate path.
_PLUGIN_FILES = (
    ".claude-plugin",
    ".mcp.json",
    "plugin.json",
    "mcp.json",
    "hooks",
    "skills",
    "scripts",
    "requirements.lock",
)
_PLUGIN_IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", "*.egg-info", ".DS_Store")
_EXECUTABLES = ("start", "ensure_uv", "capture_hook")

# The source repository publishes with a deploy key, which can push but cannot call the
# releases API. So the public repository creates its own release when the tag arrives,
# from the asset branch pushed with it, and then deletes that branch: the extension
# stays out of the history Claude Code and Codex clone. Placeholders, not str.format,
# because the workflow is full of braces.
_RELEASE_WORKFLOW = """\
# Generated by scripts/build_plugin.py in the MemorySafe source repository. Edits made
# here are replaced by the next release.
name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: @PREFIX@${{ github.ref_name }}
      - name: Publish the release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
        run: |
          if gh release view "$TAG" >/dev/null 2>&1; then
            gh release upload "$TAG" @MCPB@ --clobber
          else
            prerelease=
            case "${TAG#v}" in *[!0-9.]*) prerelease=--prerelease ;; esac
            gh release create "$TAG" @MCPB@ --verify-tag $prerelease \\
              --title "MemorySafe ${TAG#v}" --notes-file @NOTES@
          fi
      - name: Remove the asset branch
        env:
          TAG: ${{ github.ref_name }}
        run: git push origin --delete "@PREFIX@$TAG"
"""


def _release_workflow() -> str:
    return (
        _RELEASE_WORKFLOW.replace("@PREFIX@", ASSET_BRANCH_PREFIX)
        .replace("@MCPB@", MCPB_NAME)
        .replace("@NOTES@", NOTES_NAME)
    )


def _marketplace(version: str) -> dict:
    return {
        "name": MARKETPLACE_NAME,
        "owner": {"name": "MemorySafe Beta"},
        # claude plugin validate warns without it; Codex ignores it.
        "metadata": {"description": "MemorySafe: one private, local memory for Claude Code and Codex."},
        "plugins": [
            {
                "name": PLUGIN_NAME,
                "source": f"./plugins/{PLUGIN_NAME}",
                "description": "Private, governed local memory shared by Claude Code, Claude Desktop and Codex.",
                "version": version,
            }
        ],
    }


def _read_readme_template(root: Path) -> str:
    """The public README, authored as a file rather than a literal in this script.

    It lived here as `_README` until 0.4.2 and shipped for three releases missing the
    Windows migrate path, because a document inside a build script is not reviewed as
    a document. tests/test_plugin_build.py fails if it moves back.
    """
    return (root / "plugin" / "README-template.md").read_text(encoding="utf-8")


def build_plugin(root: Path, output_dir: Path) -> tuple[Path, Path]:
    version = project_version(root)
    source = root / "plugin"
    tree = output_dir / "memorysafe-plugin"
    if tree.exists():
        shutil.rmtree(tree)
    plugin = tree / "plugins" / PLUGIN_NAME
    plugin.mkdir(parents=True)

    for name in _PLUGIN_FILES:
        path = source / name
        if path.is_dir():
            shutil.copytree(path, plugin / name, ignore=_PLUGIN_IGNORE)
        else:
            shutil.copy2(path, plugin / name)
    shutil.copytree(root / "src", plugin / "src", ignore=_SRC_NOT_SHIPPED)
    _draw_icon(plugin / "assets" / "memorysafe-icon.png")
    for name in _EXECUTABLES:
        (plugin / "scripts" / name).chmod(0o755)

    (tree / ".claude-plugin").mkdir()
    (tree / ".claude-plugin" / "marketplace.json").write_text(
        json.dumps(_marketplace(version), indent=2) + "\n", encoding="utf-8"
    )
    workflows = tree / ".github" / "workflows"
    workflows.mkdir(parents=True)
    (workflows / "release.yml").write_text(_release_workflow(), encoding="utf-8")
    shutil.copy2(root / "legal" / "MemorySafe_Beta_Terms_of_Use.md", tree / "LICENSE")
    # LICENSE incorporates the Privacy Policy as part of the Terms in four places.
    # It was published nowhere, so the terms bound users to a document they could
    # not read. tests/test_plugin_build.py fails if it stops shipping.
    shutil.copy2(root / "legal" / "MemorySafe_Beta_Privacy_Policy.md", tree / "PRIVACY.md")
    # The one-image install guide the README and the release notes open with. It sits at
    # the repository root, beside the README, not in the plugin directory: every host
    # clones that directory into each install, and a guide nobody needs after installing
    # has no business in there. Its source is assets/install-guide/install-guide.html.
    shutil.copy2(root / "assets" / "install-guide" / "install-guide.png", tree / INSTALL_GUIDE)
    readme = _read_readme_template(root).format(
        version=version,
        repository=PUBLIC_REPOSITORY,
        plugin=PLUGIN_NAME,
        marketplace=MARKETPLACE_NAME,
        mcpb=MCPB_NAME,
    )
    (tree / "README.md").write_text(readme, encoding="utf-8")
    (plugin / "README.md").write_text(readme, encoding="utf-8")

    mcpb = output_dir / MCPB_NAME
    with tempfile.TemporaryDirectory(prefix="memorysafe-plugin-") as temporary:
        # One bundle builder, reused: two builders is how one of them ends up stale.
        _code_zip, desktop_bundle = build_claude_packages(root, Path(temporary))
        shutil.copy2(desktop_bundle, mcpb)
    return tree, mcpb


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    tree, mcpb = build_plugin(root, args.output_dir.expanduser().resolve())
    print(json.dumps({"marketplace_tree": str(tree), "claude_desktop": str(mcpb)}, indent=2))


if __name__ == "__main__":
    main()
